title: scratch3-bounce-around-stage
hero_image: images/banner.png
description: scratch3-bounce-around-stage description
version: 4
listed: false
copyedit: false
last_tested: "2020-08-12"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
